version: '3.9'

services:
  rag-chatbot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rag_chatbot_app
    ports:
      - "8501:8501"
    volumes:
      - ./app/data:/app/app/data
      - ./app/chroma_db:/app/app/chroma_db
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
      - GROQ_MODEL=${GROQ_MODEL}
    env_file:
      - .env
    restart: unless-stopped
